---
title: "Pre-course self reflection (SR #1)"
author: "Vedika Shirtekar"
date: 2026-01-09
format: pdf
---

## Outline your learning goals & plan:

**1. Which learning goals from the syllabus are you most excited about?**

As an avid programmer and aspiring data scientist, I am always excited to handle data to produce data-driven solutions. However, communicating data is equally important in illustrating to audiences the thought process behind analyses and decisions. I view `ggplot2` as an essential tool in crafting creative graphs that convey my purpose of understanding to a specific audience, especially when working on an analysis for a presentation. As such, two learning goals I am specifically excited about are: (1) building effective, accessible, and aesthetically-pleasing visualizations in R and with {ggplot2} + ggplot2 extension packages, and (2) provide essential, appropriate feedback on visualizations so they may be improved.

**2. What do you hope to get out of this class?**

From this course, I hope to develop complex and interactive visualizations in R for specific kinds of data, such as for fundamental chart types and enhancing visualizations. I'm especially excited to practice hands-on experience with developing visualizations in R with labs.

**3. How do you plan on accomplishing your learning goals for this course? *Note:* be specific here! Instead of writing, “I will complete homework assignments” or “I will study,” you can make these more specific strategies: “I will create a schedule to map out assignments“ (elaborate on this), “I will use the homework assignments as opportunities to practice X,” I will communicate with classmates to ask for help after trying X,” “I will participate in online learning communities, such as TidyTuesday...” etc.**

To stay on task and accomplish my learning goals, I am to effectively manage and complete time-sensitive assignments (ex. homework) and attend office hours in case I require help or have questions about how a specific visualization can be improve. Additionally, I plan to engage with online sources to further develop my data visualization skills and learn how to effectively select and organize visualizations. For example, I follow many data scientists on LinkedIn who usually post walk-throughs or blogs of data visualization tutorials in R, allowing me to learn from their experiences and compare their approaches with my own work, as well as incorporate any tips for effective visualization.
